// Code generated by "stringer -type=Opcode opcode.go"; DO NOT EDIT.

package calcutron

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HLT-0]
	_ = x[ADD-1]
	_ = x[SUB-2]
	_ = x[SUBI-3]
	_ = x[LSH-4]
	_ = x[RSH-5]
	_ = x[BRZ-6]
	_ = x[BGT-7]
	_ = x[LD-8]
	_ = x[ST-9]
	_ = x[INP-10]
	_ = x[OUT-11]
	_ = x[DEC-12]
	_ = x[INC-13]
	_ = x[ADDI-14]
	_ = x[BRA-15]
	_ = x[CLR-16]
	_ = x[MOV-17]
	_ = x[DAT-18]
}

const _Opcode_name = "HLTADDSUBSUBILSHRSHBRZBGTLDSTINPOUTDECINCADDIBRACLRMOVDAT"

var _Opcode_index = [...]uint8{0, 3, 6, 9, 13, 16, 19, 22, 25, 27, 29, 32, 35, 38, 41, 45, 48, 51, 54, 57}

func (i Opcode) String() string {
	if i >= Opcode(len(_Opcode_index)-1) {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
