// Code generated by "stringer -type=Opcode opcode.go"; DO NOT EDIT.

package prog

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JUMP-0]
	_ = x[ADD-1]
	_ = x[ADDI-2]
	_ = x[SUB-3]
	_ = x[SHIFT-4]
	_ = x[LOAD-5]
	_ = x[MOVE-6]
	_ = x[STORE-7]
	_ = x[BEQ-8]
	_ = x[BGT-9]
	_ = x[DEC-10]
	_ = x[INC-11]
	_ = x[SUBI-12]
	_ = x[BRA-13]
	_ = x[BLT-14]
	_ = x[CLEAR-15]
	_ = x[COPY-16]
	_ = x[CALL-17]
	_ = x[NOP-18]
	_ = x[HALT-19]
	_ = x[IN-20]
	_ = x[OUT-21]
	_ = x[DAT-22]
}

const _Opcode_name = "JUMPADDADDISUBSHIFTLOADMOVESTOREBEQBGTDECINCSUBIBRABLTCLEARCOPYCALLNOPHALTINOUTDAT"

var _Opcode_index = [...]uint8{0, 4, 7, 11, 14, 19, 23, 27, 32, 35, 38, 41, 44, 48, 51, 54, 59, 63, 67, 70, 74, 76, 79, 82}

func (i Opcode) String() string {
	if i >= Opcode(len(_Opcode_index)-1) {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
